import { Inter } from "next/font/google";
import "./globals.css";
import DisplayContext from "./Helpers/DisplayNavContext";
import LayoutStructure from "./Helpers/LayoutStructure";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kanban-Task-Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-full p-0 m-0 box-border custom-root-layout">
      <body
        className={`${inter.className} box-border font-sans h-full p-0 m-0 text-[var(--color-text)] bg-[var(--color-dialog)] overflow-y-hidden`}
      >
        {children}   
      </body>
    </html>
  );
}
